/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AlertCMethod2SecondaryPointLocation : IEquatable<AlertCMethod2SecondaryPointLocation>
    {
        /// <summary>
        /// Gets or Sets AlertCLocation
        /// </summary>
        [Required]
        [DataMember(Name="alertCLocation", EmitDefaultValue=false)]
        public AlertCLocation AlertCLocation { get; set; }

        /// <summary>
        /// Gets or Sets AlertCMethod2SecondaryPointLocationExtensionG
        /// </summary>
        [DataMember(Name="alertCMethod2SecondaryPointLocationExtensionG", EmitDefaultValue=false)]
        public Dictionary<string, Object> AlertCMethod2SecondaryPointLocationExtensionG { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AlertCMethod2SecondaryPointLocation {\n");
            sb.Append("  AlertCLocation: ").Append(AlertCLocation).Append("\n");
            sb.Append("  AlertCMethod2SecondaryPointLocationExtensionG: ").Append(AlertCMethod2SecondaryPointLocationExtensionG).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AlertCMethod2SecondaryPointLocation)obj);
        }

        /// <summary>
        /// Returns true if AlertCMethod2SecondaryPointLocation instances are equal
        /// </summary>
        /// <param name="other">Instance of AlertCMethod2SecondaryPointLocation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AlertCMethod2SecondaryPointLocation other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AlertCLocation == other.AlertCLocation ||
                    AlertCLocation != null &&
                    AlertCLocation.Equals(other.AlertCLocation)
                ) && 
                (
                    AlertCMethod2SecondaryPointLocationExtensionG == other.AlertCMethod2SecondaryPointLocationExtensionG ||
                    AlertCMethod2SecondaryPointLocationExtensionG != null &&
                    other.AlertCMethod2SecondaryPointLocationExtensionG != null &&
                    AlertCMethod2SecondaryPointLocationExtensionG.SequenceEqual(other.AlertCMethod2SecondaryPointLocationExtensionG)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (AlertCLocation != null)
                    hashCode = hashCode * 59 + AlertCLocation.GetHashCode();
                    if (AlertCMethod2SecondaryPointLocationExtensionG != null)
                    hashCode = hashCode * 59 + AlertCMethod2SecondaryPointLocationExtensionG.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AlertCMethod2SecondaryPointLocation left, AlertCMethod2SecondaryPointLocation right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AlertCMethod2SecondaryPointLocation left, AlertCMethod2SecondaryPointLocation right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
