/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// Gets or Sets AltitudeAccuracyEnum
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<AltitudeAccuracyEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum AltitudeAccuracyEnum
        {
            
            /// <summary>
            /// Enum EqualToOrLessThan1CentimetreEnum for equalToOrLessThan1Centimetre
            /// </summary>
            [EnumMember(Value = "equalToOrLessThan1Centimetre")]
            EqualToOrLessThan1CentimetreEnum = 1,
            
            /// <summary>
            /// Enum EqualToOrLessThan2CentimetresEnum for equalToOrLessThan2Centimetres
            /// </summary>
            [EnumMember(Value = "equalToOrLessThan2Centimetres")]
            EqualToOrLessThan2CentimetresEnum = 2,
            
            /// <summary>
            /// Enum EqualToOrLessThan5CentimetresEnum for equalToOrLessThan5Centimetres
            /// </summary>
            [EnumMember(Value = "equalToOrLessThan5Centimetres")]
            EqualToOrLessThan5CentimetresEnum = 3,
            
            /// <summary>
            /// Enum EqualToOrLessThan10CentimetresEnum for equalToOrLessThan10Centimetres
            /// </summary>
            [EnumMember(Value = "equalToOrLessThan10Centimetres")]
            EqualToOrLessThan10CentimetresEnum = 4,
            
            /// <summary>
            /// Enum EqualToOrLessThan20CentimetresEnum for equalToOrLessThan20Centimetres
            /// </summary>
            [EnumMember(Value = "equalToOrLessThan20Centimetres")]
            EqualToOrLessThan20CentimetresEnum = 5,
            
            /// <summary>
            /// Enum EqualToOrLessThan50CentimetresEnum for equalToOrLessThan50Centimetres
            /// </summary>
            [EnumMember(Value = "equalToOrLessThan50Centimetres")]
            EqualToOrLessThan50CentimetresEnum = 6,
            
            /// <summary>
            /// Enum EqualToOrLessThan1MetreEnum for equalToOrLessThan1Metre
            /// </summary>
            [EnumMember(Value = "equalToOrLessThan1Metre")]
            EqualToOrLessThan1MetreEnum = 7,
            
            /// <summary>
            /// Enum EqualToOrLessThan2MetresEnum for equalToOrLessThan2Metres
            /// </summary>
            [EnumMember(Value = "equalToOrLessThan2Metres")]
            EqualToOrLessThan2MetresEnum = 8,
            
            /// <summary>
            /// Enum EqualToOrLessThan5MetresEnum for equalToOrLessThan5Metres
            /// </summary>
            [EnumMember(Value = "equalToOrLessThan5Metres")]
            EqualToOrLessThan5MetresEnum = 9,
            
            /// <summary>
            /// Enum EqualToOrLessThan10MetresEnum for equalToOrLessThan10Metres
            /// </summary>
            [EnumMember(Value = "equalToOrLessThan10Metres")]
            EqualToOrLessThan10MetresEnum = 10,
            
            /// <summary>
            /// Enum EqualToOrLessThan20MetresEnum for equalToOrLessThan20Metres
            /// </summary>
            [EnumMember(Value = "equalToOrLessThan20Metres")]
            EqualToOrLessThan20MetresEnum = 11,
            
            /// <summary>
            /// Enum EqualToOrLessThan50MetresEnum for equalToOrLessThan50Metres
            /// </summary>
            [EnumMember(Value = "equalToOrLessThan50Metres")]
            EqualToOrLessThan50MetresEnum = 12,
            
            /// <summary>
            /// Enum EqualToOrLessThan100MetresEnum for equalToOrLessThan100Metres
            /// </summary>
            [EnumMember(Value = "equalToOrLessThan100Metres")]
            EqualToOrLessThan100MetresEnum = 13,
            
            /// <summary>
            /// Enum EqualToOrLessThan200MetresEnum for equalToOrLessThan200Metres
            /// </summary>
            [EnumMember(Value = "equalToOrLessThan200Metres")]
            EqualToOrLessThan200MetresEnum = 14,
            
            /// <summary>
            /// Enum ExtendedGEnum for extendedG
            /// </summary>
            [EnumMember(Value = "extendedG")]
            ExtendedGEnum = 15
        }
}
