/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// Gets or Sets CollisionTypeEnum
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<CollisionTypeEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum CollisionTypeEnum
        {
            
            /// <summary>
            /// Enum CollisionWithAnimalEnum for collisionWithAnimal
            /// </summary>
            [EnumMember(Value = "collisionWithAnimal")]
            CollisionWithAnimalEnum = 1,
            
            /// <summary>
            /// Enum CollisionWithObstacleEnum for collisionWithObstacle
            /// </summary>
            [EnumMember(Value = "collisionWithObstacle")]
            CollisionWithObstacleEnum = 2,
            
            /// <summary>
            /// Enum CollisionWithPersonEnum for collisionWithPerson
            /// </summary>
            [EnumMember(Value = "collisionWithPerson")]
            CollisionWithPersonEnum = 3,
            
            /// <summary>
            /// Enum HeadOnCollisionEnum for headOnCollision
            /// </summary>
            [EnumMember(Value = "headOnCollision")]
            HeadOnCollisionEnum = 4,
            
            /// <summary>
            /// Enum HeadOnOrSideCollisionEnum for headOnOrSideCollision
            /// </summary>
            [EnumMember(Value = "headOnOrSideCollision")]
            HeadOnOrSideCollisionEnum = 5,
            
            /// <summary>
            /// Enum MultipleVehicleCollisionEnum for multipleVehicleCollision
            /// </summary>
            [EnumMember(Value = "multipleVehicleCollision")]
            MultipleVehicleCollisionEnum = 6,
            
            /// <summary>
            /// Enum RearCollisionEnum for rearCollision
            /// </summary>
            [EnumMember(Value = "rearCollision")]
            RearCollisionEnum = 7,
            
            /// <summary>
            /// Enum SideCollisionEnum for sideCollision
            /// </summary>
            [EnumMember(Value = "sideCollision")]
            SideCollisionEnum = 8,
            
            /// <summary>
            /// Enum ExtendedGEnum for extendedG
            /// </summary>
            [EnumMember(Value = "extendedG")]
            ExtendedGEnum = 9
        }
}
