/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// Gets or Sets InvalidityReasonEnum
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<InvalidityReasonEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum InvalidityReasonEnum
        {
            
            /// <summary>
            /// Enum InvalidCISInformationEnum for invalidCISInformation
            /// </summary>
            [EnumMember(Value = "invalidCISInformation")]
            InvalidCISInformationEnum = 1,
            
            /// <summary>
            /// Enum InvalidClientEnum for invalidClient
            /// </summary>
            [EnumMember(Value = "invalidClient")]
            InvalidClientEnum = 2,
            
            /// <summary>
            /// Enum InvalidExchangeContextEnum for invalidExchangeContext
            /// </summary>
            [EnumMember(Value = "invalidExchangeContext")]
            InvalidExchangeContextEnum = 3,
            
            /// <summary>
            /// Enum InvalidInformationManagementEnum for invalidInformationManagement
            /// </summary>
            [EnumMember(Value = "invalidInformationManagement")]
            InvalidInformationManagementEnum = 4,
            
            /// <summary>
            /// Enum InvalidMessageEnum for invalidMessage
            /// </summary>
            [EnumMember(Value = "invalidMessage")]
            InvalidMessageEnum = 5,
            
            /// <summary>
            /// Enum InvalidPayloadEnum for invalidPayload
            /// </summary>
            [EnumMember(Value = "invalidPayload")]
            InvalidPayloadEnum = 6,
            
            /// <summary>
            /// Enum InvalidSequencingNumberEnum for invalidSequencingNumber
            /// </summary>
            [EnumMember(Value = "invalidSequencingNumber")]
            InvalidSequencingNumberEnum = 7,
            
            /// <summary>
            /// Enum InvalidSessionEnum for invalidSession
            /// </summary>
            [EnumMember(Value = "invalidSession")]
            InvalidSessionEnum = 8,
            
            /// <summary>
            /// Enum InvalidSupplierEnum for invalidSupplier
            /// </summary>
            [EnumMember(Value = "invalidSupplier")]
            InvalidSupplierEnum = 9,
            
            /// <summary>
            /// Enum OtherEnum for other
            /// </summary>
            [EnumMember(Value = "other")]
            OtherEnum = 10,
            
            /// <summary>
            /// Enum ExtendedGEnum for extendedG
            /// </summary>
            [EnumMember(Value = "extendedG")]
            ExtendedGEnum = 11
        }
}
