/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// Gets or Sets LinearDirectionEnum
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<LinearDirectionEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum LinearDirectionEnum
        {
            
            /// <summary>
            /// Enum BothEnum for both
            /// </summary>
            [EnumMember(Value = "both")]
            BothEnum = 1,
            
            /// <summary>
            /// Enum OppositeEnum for opposite
            /// </summary>
            [EnumMember(Value = "opposite")]
            OppositeEnum = 2,
            
            /// <summary>
            /// Enum AlignedEnum for aligned
            /// </summary>
            [EnumMember(Value = "aligned")]
            AlignedEnum = 3,
            
            /// <summary>
            /// Enum UnknownEnum for unknown
            /// </summary>
            [EnumMember(Value = "unknown")]
            UnknownEnum = 4,
            
            /// <summary>
            /// Enum ExtendedGEnum for extendedG
            /// </summary>
            [EnumMember(Value = "extendedG")]
            ExtendedGEnum = 5
        }
}
