/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// Gets or Sets NutsCodeTypeEnum
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<NutsCodeTypeEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum NutsCodeTypeEnum
        {
            
            /// <summary>
            /// Enum Nuts1CodeEnum for nuts1Code
            /// </summary>
            [EnumMember(Value = "nuts1Code")]
            Nuts1CodeEnum = 1,
            
            /// <summary>
            /// Enum Nuts2CodeEnum for nuts2Code
            /// </summary>
            [EnumMember(Value = "nuts2Code")]
            Nuts2CodeEnum = 2,
            
            /// <summary>
            /// Enum Nuts3CodeEnum for nuts3Code
            /// </summary>
            [EnumMember(Value = "nuts3Code")]
            Nuts3CodeEnum = 3,
            
            /// <summary>
            /// Enum Lau1CodeEnum for lau1Code
            /// </summary>
            [EnumMember(Value = "lau1Code")]
            Lau1CodeEnum = 4,
            
            /// <summary>
            /// Enum Lau2CodeEnum for lau2Code
            /// </summary>
            [EnumMember(Value = "lau2Code")]
            Lau2CodeEnum = 5,
            
            /// <summary>
            /// Enum ExtendedGEnum for extendedG
            /// </summary>
            [EnumMember(Value = "extendedG")]
            ExtendedGEnum = 6
        }
}
