/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class RoadInformationG : IEquatable<RoadInformationG>
    {
        /// <summary>
        /// Gets or Sets LocRoadInformation
        /// </summary>
        [DataMember(Name="locRoadInformation", EmitDefaultValue=false)]
        public RoadInformation LocRoadInformation { get; set; }

        /// <summary>
        /// Gets or Sets PrkRoadInformationEnhanced
        /// </summary>
        [DataMember(Name="prkRoadInformationEnhanced", EmitDefaultValue=false)]
        public RoadInformationEnhanced PrkRoadInformationEnhanced { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RoadInformationG {\n");
            sb.Append("  LocRoadInformation: ").Append(LocRoadInformation).Append("\n");
            sb.Append("  PrkRoadInformationEnhanced: ").Append(PrkRoadInformationEnhanced).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RoadInformationG)obj);
        }

        /// <summary>
        /// Returns true if RoadInformationG instances are equal
        /// </summary>
        /// <param name="other">Instance of RoadInformationG to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RoadInformationG other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    LocRoadInformation == other.LocRoadInformation ||
                    LocRoadInformation != null &&
                    LocRoadInformation.Equals(other.LocRoadInformation)
                ) && 
                (
                    PrkRoadInformationEnhanced == other.PrkRoadInformationEnhanced ||
                    PrkRoadInformationEnhanced != null &&
                    PrkRoadInformationEnhanced.Equals(other.PrkRoadInformationEnhanced)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (LocRoadInformation != null)
                    hashCode = hashCode * 59 + LocRoadInformation.GetHashCode();
                    if (PrkRoadInformationEnhanced != null)
                    hashCode = hashCode * 59 + PrkRoadInformationEnhanced.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RoadInformationG left, RoadInformationG right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RoadInformationG left, RoadInformationG right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
