/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SessionInformation : IEquatable<SessionInformation>
    {
        /// <summary>
        /// Gets or Sets SessionID
        /// </summary>
        [Required]
        [MaxLength(1024)]
        [DataMember(Name="sessionID", EmitDefaultValue=false)]
        public string SessionID { get; set; }

        /// <summary>
        /// Gets or Sets StartSession
        /// </summary>
        [DataMember(Name="startSession", EmitDefaultValue=true)]
        public DateTime StartSession { get; set; }

        /// <summary>
        /// Gets or Sets SessionInformationExtensionG
        /// </summary>
        [DataMember(Name="sessionInformationExtensionG", EmitDefaultValue=false)]
        public Dictionary<string, Object> SessionInformationExtensionG { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SessionInformation {\n");
            sb.Append("  SessionID: ").Append(SessionID).Append("\n");
            sb.Append("  StartSession: ").Append(StartSession).Append("\n");
            sb.Append("  SessionInformationExtensionG: ").Append(SessionInformationExtensionG).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SessionInformation)obj);
        }

        /// <summary>
        /// Returns true if SessionInformation instances are equal
        /// </summary>
        /// <param name="other">Instance of SessionInformation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SessionInformation other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    SessionID == other.SessionID ||
                    SessionID != null &&
                    SessionID.Equals(other.SessionID)
                ) && 
                (
                    StartSession == other.StartSession ||
                    
                    StartSession.Equals(other.StartSession)
                ) && 
                (
                    SessionInformationExtensionG == other.SessionInformationExtensionG ||
                    SessionInformationExtensionG != null &&
                    other.SessionInformationExtensionG != null &&
                    SessionInformationExtensionG.SequenceEqual(other.SessionInformationExtensionG)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (SessionID != null)
                    hashCode = hashCode * 59 + SessionID.GetHashCode();
                    
                    hashCode = hashCode * 59 + StartSession.GetHashCode();
                    if (SessionInformationExtensionG != null)
                    hashCode = hashCode * 59 + SessionInformationExtensionG.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SessionInformation left, SessionInformation right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SessionInformation left, SessionInformation right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
