/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// Gets or Sets SubdivisionTypeEnum
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<SubdivisionTypeEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum SubdivisionTypeEnum
        {
            
            /// <summary>
            /// Enum AdministrativeAtollEnum for administrativeAtoll
            /// </summary>
            [EnumMember(Value = "administrativeAtoll")]
            AdministrativeAtollEnum = 1,
            
            /// <summary>
            /// Enum AdministrativeRegionEnum for administrativeRegion
            /// </summary>
            [EnumMember(Value = "administrativeRegion")]
            AdministrativeRegionEnum = 2,
            
            /// <summary>
            /// Enum AdministrativeTerritoryEnum for administrativeTerritory
            /// </summary>
            [EnumMember(Value = "administrativeTerritory")]
            AdministrativeTerritoryEnum = 3,
            
            /// <summary>
            /// Enum ArcticRegionEnum for arcticRegion
            /// </summary>
            [EnumMember(Value = "arcticRegion")]
            ArcticRegionEnum = 4,
            
            /// <summary>
            /// Enum AutonomousCityEnum for autonomousCity
            /// </summary>
            [EnumMember(Value = "autonomousCity")]
            AutonomousCityEnum = 5,
            
            /// <summary>
            /// Enum AutonomousCityInNorthAfricaEnum for autonomousCityInNorthAfrica
            /// </summary>
            [EnumMember(Value = "autonomousCityInNorthAfrica")]
            AutonomousCityInNorthAfricaEnum = 6,
            
            /// <summary>
            /// Enum AutonomousCommunityEnum for autonomousCommunity
            /// </summary>
            [EnumMember(Value = "autonomousCommunity")]
            AutonomousCommunityEnum = 7,
            
            /// <summary>
            /// Enum AutonomousDistrictEnum for autonomousDistrict
            /// </summary>
            [EnumMember(Value = "autonomousDistrict")]
            AutonomousDistrictEnum = 8,
            
            /// <summary>
            /// Enum AutonomousProvinceEnum for autonomousProvince
            /// </summary>
            [EnumMember(Value = "autonomousProvince")]
            AutonomousProvinceEnum = 9,
            
            /// <summary>
            /// Enum AutonomousRegionEnum for autonomousRegion
            /// </summary>
            [EnumMember(Value = "autonomousRegion")]
            AutonomousRegionEnum = 10,
            
            /// <summary>
            /// Enum CantonEnum for canton
            /// </summary>
            [EnumMember(Value = "canton")]
            CantonEnum = 11,
            
            /// <summary>
            /// Enum CapitalCityEnum for capitalCity
            /// </summary>
            [EnumMember(Value = "capitalCity")]
            CapitalCityEnum = 12,
            
            /// <summary>
            /// Enum CityEnum for city
            /// </summary>
            [EnumMember(Value = "city")]
            CityEnum = 13,
            
            /// <summary>
            /// Enum CityMunicipalityEnum for cityMunicipality
            /// </summary>
            [EnumMember(Value = "cityMunicipality")]
            CityMunicipalityEnum = 14,
            
            /// <summary>
            /// Enum CityOfCountyRightEnum for cityOfCountyRight
            /// </summary>
            [EnumMember(Value = "cityOfCountyRight")]
            CityOfCountyRightEnum = 15,
            
            /// <summary>
            /// Enum CommuneEnum for commune
            /// </summary>
            [EnumMember(Value = "commune")]
            CommuneEnum = 16,
            
            /// <summary>
            /// Enum CouncilAreaEnum for councilArea
            /// </summary>
            [EnumMember(Value = "councilArea")]
            CouncilAreaEnum = 17,
            
            /// <summary>
            /// Enum CountyEnum for county
            /// </summary>
            [EnumMember(Value = "county")]
            CountyEnum = 18,
            
            /// <summary>
            /// Enum CountryEnum for country
            /// </summary>
            [EnumMember(Value = "country")]
            CountryEnum = 19,
            
            /// <summary>
            /// Enum DepartmentEnum for department
            /// </summary>
            [EnumMember(Value = "department")]
            DepartmentEnum = 20,
            
            /// <summary>
            /// Enum DependencyEnum for dependency
            /// </summary>
            [EnumMember(Value = "dependency")]
            DependencyEnum = 21,
            
            /// <summary>
            /// Enum DistrictEnum for district
            /// </summary>
            [EnumMember(Value = "district")]
            DistrictEnum = 22,
            
            /// <summary>
            /// Enum DistrictMunicipalityEnum for districtMunicipality
            /// </summary>
            [EnumMember(Value = "districtMunicipality")]
            DistrictMunicipalityEnum = 23,
            
            /// <summary>
            /// Enum DistrictWithSpecialStatusEnum for districtWithSpecialStatus
            /// </summary>
            [EnumMember(Value = "districtWithSpecialStatus")]
            DistrictWithSpecialStatusEnum = 24,
            
            /// <summary>
            /// Enum EntityEnum for entity
            /// </summary>
            [EnumMember(Value = "entity")]
            EntityEnum = 25,
            
            /// <summary>
            /// Enum GeographicalEntityEnum for geographicalEntity
            /// </summary>
            [EnumMember(Value = "geographicalEntity")]
            GeographicalEntityEnum = 26,
            
            /// <summary>
            /// Enum GovernorateEnum for governorate
            /// </summary>
            [EnumMember(Value = "governorate")]
            GovernorateEnum = 27,
            
            /// <summary>
            /// Enum LaenderEnum for laender
            /// </summary>
            [EnumMember(Value = "laender")]
            LaenderEnum = 28,
            
            /// <summary>
            /// Enum LocalCouncilEnum for localCouncil
            /// </summary>
            [EnumMember(Value = "localCouncil")]
            LocalCouncilEnum = 29,
            
            /// <summary>
            /// Enum LondonBoroughEnum for londonBorough
            /// </summary>
            [EnumMember(Value = "londonBorough")]
            LondonBoroughEnum = 30,
            
            /// <summary>
            /// Enum MetropolitanAreaEnum for metropolitanArea
            /// </summary>
            [EnumMember(Value = "metropolitanArea")]
            MetropolitanAreaEnum = 31,
            
            /// <summary>
            /// Enum MetropolitanDepartmentEnum for metropolitanDepartment
            /// </summary>
            [EnumMember(Value = "metropolitanDepartment")]
            MetropolitanDepartmentEnum = 32,
            
            /// <summary>
            /// Enum MetropolitanDistrictEnum for metropolitanDistrict
            /// </summary>
            [EnumMember(Value = "metropolitanDistrict")]
            MetropolitanDistrictEnum = 33,
            
            /// <summary>
            /// Enum MetropolitanRegionEnum for metropolitanRegion
            /// </summary>
            [EnumMember(Value = "metropolitanRegion")]
            MetropolitanRegionEnum = 34,
            
            /// <summary>
            /// Enum MunicipalityEnum for municipality
            /// </summary>
            [EnumMember(Value = "municipality")]
            MunicipalityEnum = 35,
            
            /// <summary>
            /// Enum OverseasDepartmentEnum for overseasDepartment
            /// </summary>
            [EnumMember(Value = "overseasDepartment")]
            OverseasDepartmentEnum = 36,
            
            /// <summary>
            /// Enum OverseasRegionEnum for overseasRegion
            /// </summary>
            [EnumMember(Value = "overseasRegion")]
            OverseasRegionEnum = 37,
            
            /// <summary>
            /// Enum OverseasTerritorialCollectivityEnum for overseasTerritorialCollectivity
            /// </summary>
            [EnumMember(Value = "overseasTerritorialCollectivity")]
            OverseasTerritorialCollectivityEnum = 38,
            
            /// <summary>
            /// Enum ParishEnum for parish
            /// </summary>
            [EnumMember(Value = "parish")]
            ParishEnum = 39,
            
            /// <summary>
            /// Enum ProvinceEnum for province
            /// </summary>
            [EnumMember(Value = "province")]
            ProvinceEnum = 40,
            
            /// <summary>
            /// Enum QuarterEnum for quarter
            /// </summary>
            [EnumMember(Value = "quarter")]
            QuarterEnum = 41,
            
            /// <summary>
            /// Enum RegionEnum for region
            /// </summary>
            [EnumMember(Value = "region")]
            RegionEnum = 42,
            
            /// <summary>
            /// Enum RepublicEnum for republic
            /// </summary>
            [EnumMember(Value = "republic")]
            RepublicEnum = 43,
            
            /// <summary>
            /// Enum RepublicanCityEnum for republicanCity
            /// </summary>
            [EnumMember(Value = "republicanCity")]
            RepublicanCityEnum = 44,
            
            /// <summary>
            /// Enum SelfGovernedPartEnum for selfGovernedPart
            /// </summary>
            [EnumMember(Value = "selfGovernedPart")]
            SelfGovernedPartEnum = 45,
            
            /// <summary>
            /// Enum SpecialMunicipalityEnum for specialMunicipality
            /// </summary>
            [EnumMember(Value = "specialMunicipality")]
            SpecialMunicipalityEnum = 46,
            
            /// <summary>
            /// Enum StateEnum for state
            /// </summary>
            [EnumMember(Value = "state")]
            StateEnum = 47,
            
            /// <summary>
            /// Enum TerritorialUnitEnum for territorialUnit
            /// </summary>
            [EnumMember(Value = "territorialUnit")]
            TerritorialUnitEnum = 48,
            
            /// <summary>
            /// Enum TerritoryEnum for territory
            /// </summary>
            [EnumMember(Value = "territory")]
            TerritoryEnum = 49,
            
            /// <summary>
            /// Enum TwoTierCountyEnum for twoTierCounty
            /// </summary>
            [EnumMember(Value = "twoTierCounty")]
            TwoTierCountyEnum = 50,
            
            /// <summary>
            /// Enum UnitaryAuthorityEnum for unitaryAuthority
            /// </summary>
            [EnumMember(Value = "unitaryAuthority")]
            UnitaryAuthorityEnum = 51,
            
            /// <summary>
            /// Enum WardEnum for ward
            /// </summary>
            [EnumMember(Value = "ward")]
            WardEnum = 52,
            
            /// <summary>
            /// Enum OtherEnum for other
            /// </summary>
            [EnumMember(Value = "other")]
            OtherEnum = 53,
            
            /// <summary>
            /// Enum ExtendedGEnum for extendedG
            /// </summary>
            [EnumMember(Value = "extendedG")]
            ExtendedGEnum = 54
        }
}
