/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// Gets or Sets VehicleEquipmentEnum
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<VehicleEquipmentEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum VehicleEquipmentEnum
        {
            
            /// <summary>
            /// Enum NotUsingSnowChainsEnum for notUsingSnowChains
            /// </summary>
            [EnumMember(Value = "notUsingSnowChains")]
            NotUsingSnowChainsEnum = 1,
            
            /// <summary>
            /// Enum NotUsingSnowChainsOrTyresEnum for notUsingSnowChainsOrTyres
            /// </summary>
            [EnumMember(Value = "notUsingSnowChainsOrTyres")]
            NotUsingSnowChainsOrTyresEnum = 2,
            
            /// <summary>
            /// Enum SnowChainsInUseEnum for snowChainsInUse
            /// </summary>
            [EnumMember(Value = "snowChainsInUse")]
            SnowChainsInUseEnum = 3,
            
            /// <summary>
            /// Enum SnowTyresInUseEnum for snowTyresInUse
            /// </summary>
            [EnumMember(Value = "snowTyresInUse")]
            SnowTyresInUseEnum = 4,
            
            /// <summary>
            /// Enum SnowChainsOrTyresInUseEnum for snowChainsOrTyresInUse
            /// </summary>
            [EnumMember(Value = "snowChainsOrTyresInUse")]
            SnowChainsOrTyresInUseEnum = 5,
            
            /// <summary>
            /// Enum WithoutSnowTyresOrChainsOnBoardEnum for withoutSnowTyresOrChainsOnBoard
            /// </summary>
            [EnumMember(Value = "withoutSnowTyresOrChainsOnBoard")]
            WithoutSnowTyresOrChainsOnBoardEnum = 6,
            
            /// <summary>
            /// Enum ExtendedGEnum for extendedG
            /// </summary>
            [EnumMember(Value = "extendedG")]
            ExtendedGEnum = 7
        }
}
