/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class WidthCharacteristic : IEquatable<WidthCharacteristic>
    {
        /// <summary>
        /// Gets or Sets ComparisonOperator
        /// </summary>
        [Required]
        [DataMember(Name="comparisonOperator", EmitDefaultValue=false)]
        public ComparisonOperatorEnumG ComparisonOperator { get; set; }

        /// <summary>
        /// Gets or Sets VehicleWidth
        /// </summary>
        [Required]
        [DataMember(Name="vehicleWidth", EmitDefaultValue=true)]
        public decimal VehicleWidth { get; set; }

        /// <summary>
        /// Gets or Sets WidthCharacteristicExtensionG
        /// </summary>
        [DataMember(Name="widthCharacteristicExtensionG", EmitDefaultValue=false)]
        public Dictionary<string, Object> WidthCharacteristicExtensionG { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WidthCharacteristic {\n");
            sb.Append("  ComparisonOperator: ").Append(ComparisonOperator).Append("\n");
            sb.Append("  VehicleWidth: ").Append(VehicleWidth).Append("\n");
            sb.Append("  WidthCharacteristicExtensionG: ").Append(WidthCharacteristicExtensionG).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((WidthCharacteristic)obj);
        }

        /// <summary>
        /// Returns true if WidthCharacteristic instances are equal
        /// </summary>
        /// <param name="other">Instance of WidthCharacteristic to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WidthCharacteristic other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ComparisonOperator == other.ComparisonOperator ||
                    ComparisonOperator != null &&
                    ComparisonOperator.Equals(other.ComparisonOperator)
                ) && 
                (
                    VehicleWidth == other.VehicleWidth ||
                    
                    VehicleWidth.Equals(other.VehicleWidth)
                ) && 
                (
                    WidthCharacteristicExtensionG == other.WidthCharacteristicExtensionG ||
                    WidthCharacteristicExtensionG != null &&
                    other.WidthCharacteristicExtensionG != null &&
                    WidthCharacteristicExtensionG.SequenceEqual(other.WidthCharacteristicExtensionG)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ComparisonOperator != null)
                    hashCode = hashCode * 59 + ComparisonOperator.GetHashCode();
                    
                    hashCode = hashCode * 59 + VehicleWidth.GetHashCode();
                    if (WidthCharacteristicExtensionG != null)
                    hashCode = hashCode * 59 + WidthCharacteristicExtensionG.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(WidthCharacteristic left, WidthCharacteristic right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(WidthCharacteristic left, WidthCharacteristic right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
