from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class AltitudeAccuracyEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    EQUALTOORLESSTHAN1CENTIMETRE = 'equalToOrLessThan1Centimetre'
    EQUALTOORLESSTHAN2CENTIMETRES = 'equalToOrLessThan2Centimetres'
    EQUALTOORLESSTHAN5CENTIMETRES = 'equalToOrLessThan5Centimetres'
    EQUALTOORLESSTHAN10CENTIMETRES = 'equalToOrLessThan10Centimetres'
    EQUALTOORLESSTHAN20CENTIMETRES = 'equalToOrLessThan20Centimetres'
    EQUALTOORLESSTHAN50CENTIMETRES = 'equalToOrLessThan50Centimetres'
    EQUALTOORLESSTHAN1METRE = 'equalToOrLessThan1Metre'
    EQUALTOORLESSTHAN2METRES = 'equalToOrLessThan2Metres'
    EQUALTOORLESSTHAN5METRES = 'equalToOrLessThan5Metres'
    EQUALTOORLESSTHAN10METRES = 'equalToOrLessThan10Metres'
    EQUALTOORLESSTHAN20METRES = 'equalToOrLessThan20Metres'
    EQUALTOORLESSTHAN50METRES = 'equalToOrLessThan50Metres'
    EQUALTOORLESSTHAN100METRES = 'equalToOrLessThan100Metres'
    EQUALTOORLESSTHAN200METRES = 'equalToOrLessThan200Metres'
    EXTENDEDG = 'extendedG'
    def __init__(self):  # noqa: E501
        """AltitudeAccuracyEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'AltitudeAccuracyEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AltitudeAccuracyEnum of this AltitudeAccuracyEnum.  # noqa: E501
        :rtype: AltitudeAccuracyEnum
        """
        return util.deserialize_model(dikt, cls)
