from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.exchange_status_enum_g import ExchangeStatusEnumG
from openapi_server.models.multilingual_string import MultilingualString
from openapi_server.models.return_information import ReturnInformation
from openapi_server.models.session_information import SessionInformation
from openapi_server import util

from openapi_server.models.exchange_status_enum_g import ExchangeStatusEnumG  # noqa: E501
from openapi_server.models.multilingual_string import MultilingualString  # noqa: E501
from openapi_server.models.return_information import ReturnInformation  # noqa: E501
from openapi_server.models.session_information import SessionInformation  # noqa: E501

class DynamicInformation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, exchange_status=None, exchange_status_description=None, completed_paylod=None, message_sequencing_number=None, message_generation_timestamp=None, return_information=None, session_information=None, dynamic_information_extension_g=None):  # noqa: E501
        """DynamicInformation - a model defined in OpenAPI

        :param exchange_status: The exchange_status of this DynamicInformation.  # noqa: E501
        :type exchange_status: ExchangeStatusEnumG
        :param exchange_status_description: The exchange_status_description of this DynamicInformation.  # noqa: E501
        :type exchange_status_description: MultilingualString
        :param completed_paylod: The completed_paylod of this DynamicInformation.  # noqa: E501
        :type completed_paylod: bool
        :param message_sequencing_number: The message_sequencing_number of this DynamicInformation.  # noqa: E501
        :type message_sequencing_number: int
        :param message_generation_timestamp: The message_generation_timestamp of this DynamicInformation.  # noqa: E501
        :type message_generation_timestamp: datetime
        :param return_information: The return_information of this DynamicInformation.  # noqa: E501
        :type return_information: ReturnInformation
        :param session_information: The session_information of this DynamicInformation.  # noqa: E501
        :type session_information: SessionInformation
        :param dynamic_information_extension_g: The dynamic_information_extension_g of this DynamicInformation.  # noqa: E501
        :type dynamic_information_extension_g: Dict[str, object]
        """
        self.openapi_types = {
            'exchange_status': ExchangeStatusEnumG,
            'exchange_status_description': MultilingualString,
            'completed_paylod': bool,
            'message_sequencing_number': int,
            'message_generation_timestamp': datetime,
            'return_information': ReturnInformation,
            'session_information': SessionInformation,
            'dynamic_information_extension_g': Dict[str, object]
        }

        self.attribute_map = {
            'exchange_status': 'exchangeStatus',
            'exchange_status_description': 'exchangeStatusDescription',
            'completed_paylod': 'completedPaylod',
            'message_sequencing_number': 'messageSequencingNumber',
            'message_generation_timestamp': 'messageGenerationTimestamp',
            'return_information': 'returnInformation',
            'session_information': 'sessionInformation',
            'dynamic_information_extension_g': 'dynamicInformationExtensionG'
        }

        self._exchange_status = exchange_status
        self._exchange_status_description = exchange_status_description
        self._completed_paylod = completed_paylod
        self._message_sequencing_number = message_sequencing_number
        self._message_generation_timestamp = message_generation_timestamp
        self._return_information = return_information
        self._session_information = session_information
        self._dynamic_information_extension_g = dynamic_information_extension_g

    @classmethod
    def from_dict(cls, dikt) -> 'DynamicInformation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DynamicInformation of this DynamicInformation.  # noqa: E501
        :rtype: DynamicInformation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def exchange_status(self) -> ExchangeStatusEnumG:
        """Gets the exchange_status of this DynamicInformation.


        :return: The exchange_status of this DynamicInformation.
        :rtype: ExchangeStatusEnumG
        """
        return self._exchange_status

    @exchange_status.setter
    def exchange_status(self, exchange_status: ExchangeStatusEnumG):
        """Sets the exchange_status of this DynamicInformation.


        :param exchange_status: The exchange_status of this DynamicInformation.
        :type exchange_status: ExchangeStatusEnumG
        """
        if exchange_status is None:
            raise ValueError("Invalid value for `exchange_status`, must not be `None`")  # noqa: E501

        self._exchange_status = exchange_status

    @property
    def exchange_status_description(self) -> MultilingualString:
        """Gets the exchange_status_description of this DynamicInformation.


        :return: The exchange_status_description of this DynamicInformation.
        :rtype: MultilingualString
        """
        return self._exchange_status_description

    @exchange_status_description.setter
    def exchange_status_description(self, exchange_status_description: MultilingualString):
        """Sets the exchange_status_description of this DynamicInformation.


        :param exchange_status_description: The exchange_status_description of this DynamicInformation.
        :type exchange_status_description: MultilingualString
        """

        self._exchange_status_description = exchange_status_description

    @property
    def completed_paylod(self) -> bool:
        """Gets the completed_paylod of this DynamicInformation.


        :return: The completed_paylod of this DynamicInformation.
        :rtype: bool
        """
        return self._completed_paylod

    @completed_paylod.setter
    def completed_paylod(self, completed_paylod: bool):
        """Sets the completed_paylod of this DynamicInformation.


        :param completed_paylod: The completed_paylod of this DynamicInformation.
        :type completed_paylod: bool
        """

        self._completed_paylod = completed_paylod

    @property
    def message_sequencing_number(self) -> int:
        """Gets the message_sequencing_number of this DynamicInformation.


        :return: The message_sequencing_number of this DynamicInformation.
        :rtype: int
        """
        return self._message_sequencing_number

    @message_sequencing_number.setter
    def message_sequencing_number(self, message_sequencing_number: int):
        """Sets the message_sequencing_number of this DynamicInformation.


        :param message_sequencing_number: The message_sequencing_number of this DynamicInformation.
        :type message_sequencing_number: int
        """
        if message_sequencing_number is not None and message_sequencing_number < 0:  # noqa: E501
            raise ValueError("Invalid value for `message_sequencing_number`, must be a value greater than or equal to `0`")  # noqa: E501

        self._message_sequencing_number = message_sequencing_number

    @property
    def message_generation_timestamp(self) -> datetime:
        """Gets the message_generation_timestamp of this DynamicInformation.


        :return: The message_generation_timestamp of this DynamicInformation.
        :rtype: datetime
        """
        return self._message_generation_timestamp

    @message_generation_timestamp.setter
    def message_generation_timestamp(self, message_generation_timestamp: datetime):
        """Sets the message_generation_timestamp of this DynamicInformation.


        :param message_generation_timestamp: The message_generation_timestamp of this DynamicInformation.
        :type message_generation_timestamp: datetime
        """
        if message_generation_timestamp is None:
            raise ValueError("Invalid value for `message_generation_timestamp`, must not be `None`")  # noqa: E501

        self._message_generation_timestamp = message_generation_timestamp

    @property
    def return_information(self) -> ReturnInformation:
        """Gets the return_information of this DynamicInformation.


        :return: The return_information of this DynamicInformation.
        :rtype: ReturnInformation
        """
        return self._return_information

    @return_information.setter
    def return_information(self, return_information: ReturnInformation):
        """Sets the return_information of this DynamicInformation.


        :param return_information: The return_information of this DynamicInformation.
        :type return_information: ReturnInformation
        """

        self._return_information = return_information

    @property
    def session_information(self) -> SessionInformation:
        """Gets the session_information of this DynamicInformation.


        :return: The session_information of this DynamicInformation.
        :rtype: SessionInformation
        """
        return self._session_information

    @session_information.setter
    def session_information(self, session_information: SessionInformation):
        """Sets the session_information of this DynamicInformation.


        :param session_information: The session_information of this DynamicInformation.
        :type session_information: SessionInformation
        """

        self._session_information = session_information

    @property
    def dynamic_information_extension_g(self) -> Dict[str, object]:
        """Gets the dynamic_information_extension_g of this DynamicInformation.


        :return: The dynamic_information_extension_g of this DynamicInformation.
        :rtype: Dict[str, object]
        """
        return self._dynamic_information_extension_g

    @dynamic_information_extension_g.setter
    def dynamic_information_extension_g(self, dynamic_information_extension_g: Dict[str, object]):
        """Sets the dynamic_information_extension_g of this DynamicInformation.


        :param dynamic_information_extension_g: The dynamic_information_extension_g of this DynamicInformation.
        :type dynamic_information_extension_g: Dict[str, object]
        """

        self._dynamic_information_extension_g = dynamic_information_extension_g
