from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class InvalidityReasonEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    INVALIDCISINFORMATION = 'invalidCISInformation'
    INVALIDCLIENT = 'invalidClient'
    INVALIDEXCHANGECONTEXT = 'invalidExchangeContext'
    INVALIDINFORMATIONMANAGEMENT = 'invalidInformationManagement'
    INVALIDMESSAGE = 'invalidMessage'
    INVALIDPAYLOAD = 'invalidPayload'
    INVALIDSEQUENCINGNUMBER = 'invalidSequencingNumber'
    INVALIDSESSION = 'invalidSession'
    INVALIDSUPPLIER = 'invalidSupplier'
    OTHER = 'other'
    EXTENDEDG = 'extendedG'
    def __init__(self):  # noqa: E501
        """InvalidityReasonEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'InvalidityReasonEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InvalidityReasonEnum of this InvalidityReasonEnum.  # noqa: E501
        :rtype: InvalidityReasonEnum
        """
        return util.deserialize_model(dikt, cls)
