from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class NamedAreaTypeEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    APPLICATIONREGION = 'applicationRegion'
    CONTINENT = 'continent'
    COUNTRY = 'country'
    COUNTRYGROUP = 'countryGroup'
    CARPARKAREA = 'carParkArea'
    CARPOOLAREA = 'carpoolArea'
    FUZZYAREA = 'fuzzyArea'
    INDUSTRIALAREA = 'industrialArea'
    LAKE = 'lake'
    METEOROLOGICALAREA = 'meteorologicalArea'
    METROPOLITANAREA = 'metropolitanArea'
    MUNICIPALITY = 'municipality'
    PARKANDRIDESITE = 'parkAndRideSite'
    RURALCOUNTY = 'ruralCounty'
    SEA = 'sea'
    TOURISTAREA = 'touristArea'
    TRAFFICAREA = 'trafficArea'
    URBANCOUNTY = 'urbanCounty'
    ORDER1ADMINISTRATIVEAREA = 'order1AdministrativeArea'
    ORDER2ADMINISTRATIVEAREA = 'order2AdministrativeArea'
    ORDER3ADMINISTRATIVEAREA = 'order3AdministrativeArea'
    ORDER4ADMINISTRATIVEAREA = 'order4AdministrativeArea'
    ORDER5ADMINISTRATIVEAREA = 'order5AdministrativeArea'
    POLICEFORCECONTROLAREA = 'policeForceControlArea'
    ROADOPERATORCONTROLAREA = 'roadOperatorControlArea'
    WATERAREA = 'waterArea'
    EXTENDEDG = 'extendedG'
    def __init__(self):  # noqa: E501
        """NamedAreaTypeEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'NamedAreaTypeEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NamedAreaTypeEnum of this NamedAreaTypeEnum.  # noqa: E501
        :rtype: NamedAreaTypeEnum
        """
        return util.deserialize_model(dikt, cls)
