from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class NamedAreaExtended(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, named_area_code=None):  # noqa: E501
        """NamedAreaExtended - a model defined in OpenAPI

        :param named_area_code: The named_area_code of this NamedAreaExtended.  # noqa: E501
        :type named_area_code: str
        """
        self.openapi_types = {
            'named_area_code': str
        }

        self.attribute_map = {
            'named_area_code': 'namedAreaCode'
        }

        self._named_area_code = named_area_code

    @classmethod
    def from_dict(cls, dikt) -> 'NamedAreaExtended':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NamedAreaExtended of this NamedAreaExtended.  # noqa: E501
        :rtype: NamedAreaExtended
        """
        return util.deserialize_model(dikt, cls)

    @property
    def named_area_code(self) -> str:
        """Gets the named_area_code of this NamedAreaExtended.


        :return: The named_area_code of this NamedAreaExtended.
        :rtype: str
        """
        return self._named_area_code

    @named_area_code.setter
    def named_area_code(self, named_area_code: str):
        """Sets the named_area_code of this NamedAreaExtended.


        :param named_area_code: The named_area_code of this NamedAreaExtended.
        :type named_area_code: str
        """
        if named_area_code is None:
            raise ValueError("Invalid value for `named_area_code`, must not be `None`")  # noqa: E501
        if named_area_code is not None and len(named_area_code) > 1024:
            raise ValueError("Invalid value for `named_area_code`, length must be less than or equal to `1024`")  # noqa: E501

        self._named_area_code = named_area_code
