from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class NutsCodeTypeEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NUTS1CODE = 'nuts1Code'
    NUTS2CODE = 'nuts2Code'
    NUTS3CODE = 'nuts3Code'
    LAU1CODE = 'lau1Code'
    LAU2CODE = 'lau2Code'
    EXTENDEDG = 'extendedG'
    def __init__(self):  # noqa: E501
        """NutsCodeTypeEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'NutsCodeTypeEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NutsCodeTypeEnum of this NutsCodeTypeEnum.  # noqa: E501
        :rtype: NutsCodeTypeEnum
        """
        return util.deserialize_model(dikt, cls)
