from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ProtocolTypeEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DELTAPULL = 'deltaPull'
    DELTAPUSH = 'deltaPush'
    OTHER = 'other'
    SIMPLECIS = 'simpleCIS'
    SIMPLEPUSH = 'simplePush'
    SNAPSHOTPULL = 'snapshotPull'
    SNAPSHOTPUSH = 'snapshotPush'
    STATEFULCIS = 'statefulCIS'
    STATEFULPUSH = 'statefulPush'
    EXTENDEDG = 'extendedG'
    def __init__(self):  # noqa: E501
        """ProtocolTypeEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ProtocolTypeEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProtocolTypeEnum of this ProtocolTypeEnum.  # noqa: E501
        :rtype: ProtocolTypeEnum
        """
        return util.deserialize_model(dikt, cls)
