from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class RoadTypeEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    MOTORWAY = 'motorway'
    TRUNKROAD = 'trunkRoad'
    MAINROAD = 'mainRoad'
    OTHER = 'other'
    EXTENDEDG = 'extendedG'
    def __init__(self):  # noqa: E501
        """RoadTypeEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'RoadTypeEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RoadTypeEnum of this RoadTypeEnum.  # noqa: E501
        :rtype: RoadTypeEnum
        """
        return util.deserialize_model(dikt, cls)
