from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ServiceActionEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AGREEMENT = 'agreement'
    CANCELLATION = 'cancellation'
    IMPLEMENTATION = 'implementation'
    PROCESSING = 'processing'
    STATUSINFORMATION = 'statusInformation'
    TERMINATION = 'termination'
    EXTENDEDG = 'extendedG'
    def __init__(self):  # noqa: E501
        """ServiceActionEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceActionEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceActionEnum of this ServiceActionEnum.  # noqa: E501
        :rtype: ServiceActionEnum
        """
        return util.deserialize_model(dikt, cls)
