from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SubdivisionTypeEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ADMINISTRATIVEATOLL = 'administrativeAtoll'
    ADMINISTRATIVEREGION = 'administrativeRegion'
    ADMINISTRATIVETERRITORY = 'administrativeTerritory'
    ARCTICREGION = 'arcticRegion'
    AUTONOMOUSCITY = 'autonomousCity'
    AUTONOMOUSCITYINNORTHAFRICA = 'autonomousCityInNorthAfrica'
    AUTONOMOUSCOMMUNITY = 'autonomousCommunity'
    AUTONOMOUSDISTRICT = 'autonomousDistrict'
    AUTONOMOUSPROVINCE = 'autonomousProvince'
    AUTONOMOUSREGION = 'autonomousRegion'
    CANTON = 'canton'
    CAPITALCITY = 'capitalCity'
    CITY = 'city'
    CITYMUNICIPALITY = 'cityMunicipality'
    CITYOFCOUNTYRIGHT = 'cityOfCountyRight'
    COMMUNE = 'commune'
    COUNCILAREA = 'councilArea'
    COUNTY = 'county'
    COUNTRY = 'country'
    DEPARTMENT = 'department'
    DEPENDENCY = 'dependency'
    DISTRICT = 'district'
    DISTRICTMUNICIPALITY = 'districtMunicipality'
    DISTRICTWITHSPECIALSTATUS = 'districtWithSpecialStatus'
    ENTITY = 'entity'
    GEOGRAPHICALENTITY = 'geographicalEntity'
    GOVERNORATE = 'governorate'
    LAENDER = 'laender'
    LOCALCOUNCIL = 'localCouncil'
    LONDONBOROUGH = 'londonBorough'
    METROPOLITANAREA = 'metropolitanArea'
    METROPOLITANDEPARTMENT = 'metropolitanDepartment'
    METROPOLITANDISTRICT = 'metropolitanDistrict'
    METROPOLITANREGION = 'metropolitanRegion'
    MUNICIPALITY = 'municipality'
    OVERSEASDEPARTMENT = 'overseasDepartment'
    OVERSEASREGION = 'overseasRegion'
    OVERSEASTERRITORIALCOLLECTIVITY = 'overseasTerritorialCollectivity'
    PARISH = 'parish'
    PROVINCE = 'province'
    QUARTER = 'quarter'
    REGION = 'region'
    REPUBLIC = 'republic'
    REPUBLICANCITY = 'republicanCity'
    SELFGOVERNEDPART = 'selfGovernedPart'
    SPECIALMUNICIPALITY = 'specialMunicipality'
    STATE = 'state'
    TERRITORIALUNIT = 'territorialUnit'
    TERRITORY = 'territory'
    TWOTIERCOUNTY = 'twoTierCounty'
    UNITARYAUTHORITY = 'unitaryAuthority'
    WARD = 'ward'
    OTHER = 'other'
    EXTENDEDG = 'extendedG'
    def __init__(self):  # noqa: E501
        """SubdivisionTypeEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'SubdivisionTypeEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubdivisionTypeEnum of this SubdivisionTypeEnum.  # noqa: E501
        :rtype: SubdivisionTypeEnum
        """
        return util.deserialize_model(dikt, cls)
