from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class VehicleStatusEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ABANDONED = 'abandoned'
    BROKENDOWN = 'brokenDown'
    BURNTOUT = 'burntOut'
    DAMAGED = 'damaged'
    DAMAGEDANDIMMOBILIZED = 'damagedAndImmobilized'
    INDITCH = 'inDitch'
    JACKNIFED = 'jacknifed'
    OFFROAD = 'offRoad'
    ONFIRE = 'onFire'
    ONTOPOFCRASHBARRIER = 'onTopOfCrashBarrier'
    ONWHEELS = 'onWheels'
    OVERTURNED = 'overturned'
    ROLLABLE = 'rollable'
    SPUNAROUND = 'spunAround'
    EXTENDEDG = 'extendedG'
    def __init__(self):  # noqa: E501
        """VehicleStatusEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'VehicleStatusEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VehicleStatusEnum of this VehicleStatusEnum.  # noqa: E501
        :rtype: VehicleStatusEnum
        """
        return util.deserialize_model(dikt, cls)
