from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class VehicleUsageEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AGRICULTURAL = 'agricultural'
    CARSHARING = 'carSharing'
    CITYLOGISTICS = 'cityLogistics'
    COMMERCIAL = 'commercial'
    EMERGENCYSERVICES = 'emergencyServices'
    MILITARY = 'military'
    NONCOMMERCIAL = 'nonCommercial'
    PATROL = 'patrol'
    RECOVERYSERVICES = 'recoveryServices'
    ROADMAINTENANCEORCONSTRUCTION = 'roadMaintenanceOrConstruction'
    ROADOPERATOR = 'roadOperator'
    TAXI = 'taxi'
    EXTENDEDG = 'extendedG'
    def __init__(self):  # noqa: E501
        """VehicleUsageEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'VehicleUsageEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VehicleUsageEnum of this VehicleUsageEnum.  # noqa: E501
        :rtype: VehicleUsageEnum
        """
        return util.deserialize_model(dikt, cls)
