from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class VehicleEquipmentEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NOTUSINGSNOWCHAINS = 'notUsingSnowChains'
    NOTUSINGSNOWCHAINSORTYRES = 'notUsingSnowChainsOrTyres'
    SNOWCHAINSINUSE = 'snowChainsInUse'
    SNOWTYRESINUSE = 'snowTyresInUse'
    SNOWCHAINSORTYRESINUSE = 'snowChainsOrTyresInUse'
    WITHOUTSNOWTYRESORCHAINSONBOARD = 'withoutSnowTyresOrChainsOnBoard'
    EXTENDEDG = 'extendedG'
    def __init__(self):  # noqa: E501
        """VehicleEquipmentEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'VehicleEquipmentEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VehicleEquipmentEnum of this VehicleEquipmentEnum.  # noqa: E501
        :rtype: VehicleEquipmentEnum
        """
        return util.deserialize_model(dikt, cls)
