from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.vehicle_type_enum import VehicleTypeEnum
from openapi_server.models.vehicle_type_enum_extension_type_g import VehicleTypeEnumExtensionTypeG
from openapi_server import util

from openapi_server.models.vehicle_type_enum import VehicleTypeEnum  # noqa: E501
from openapi_server.models.vehicle_type_enum_extension_type_g import VehicleTypeEnumExtensionTypeG  # noqa: E501

class VehicleTypeEnumG(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, value=None, extended_value_g=None):  # noqa: E501
        """VehicleTypeEnumG - a model defined in OpenAPI

        :param value: The value of this VehicleTypeEnumG.  # noqa: E501
        :type value: VehicleTypeEnum
        :param extended_value_g: The extended_value_g of this VehicleTypeEnumG.  # noqa: E501
        :type extended_value_g: VehicleTypeEnumExtensionTypeG
        """
        self.openapi_types = {
            'value': VehicleTypeEnum,
            'extended_value_g': VehicleTypeEnumExtensionTypeG
        }

        self.attribute_map = {
            'value': 'value',
            'extended_value_g': 'extendedValueG'
        }

        self._value = value
        self._extended_value_g = extended_value_g

    @classmethod
    def from_dict(cls, dikt) -> 'VehicleTypeEnumG':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VehicleTypeEnumG of this VehicleTypeEnumG.  # noqa: E501
        :rtype: VehicleTypeEnumG
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> VehicleTypeEnum:
        """Gets the value of this VehicleTypeEnumG.


        :return: The value of this VehicleTypeEnumG.
        :rtype: VehicleTypeEnum
        """
        return self._value

    @value.setter
    def value(self, value: VehicleTypeEnum):
        """Sets the value of this VehicleTypeEnumG.


        :param value: The value of this VehicleTypeEnumG.
        :type value: VehicleTypeEnum
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def extended_value_g(self) -> VehicleTypeEnumExtensionTypeG:
        """Gets the extended_value_g of this VehicleTypeEnumG.


        :return: The extended_value_g of this VehicleTypeEnumG.
        :rtype: VehicleTypeEnumExtensionTypeG
        """
        return self._extended_value_g

    @extended_value_g.setter
    def extended_value_g(self, extended_value_g: VehicleTypeEnumExtensionTypeG):
        """Sets the extended_value_g of this VehicleTypeEnumG.


        :param extended_value_g: The extended_value_g of this VehicleTypeEnumG.
        :type extended_value_g: VehicleTypeEnumExtensionTypeG
        """

        self._extended_value_g = extended_value_g
