@LOCALBASEURL = https://localhost:44301
@EXTERNALURL = https://upgraded-space-cod-4rjxv94jqgg35grj-44301.app.github.dev/

## Call local http GET server
GET {{LOCALBASEURL}}/datexpull/1.0.2/pull
User-Agent: rest-client
Content-Type: application/xml

###
#Get OpenAPI page
GET {{LOCALBASEURL}}/datexpull
User-Agent: rest-client

###
#Get OpenAPI spec
GET {{LOCALBASEURL}}/datexpull/1.0.2/openapi.json
User-Agent: rest-client

###
#Get keepAlive external
GET {{EXTERNALURL}}/datexpull/1.0.2/keepalive
User-Agent: rest-client


###
#Get keepAlive internal
GET {{LOCALBASEURL}}/datexpull/1.0.2/keepalive
User-Agent: rest-client