/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Carriageway : IEquatable<Carriageway>
    {
        /// <summary>
        /// Gets or Sets VarCarriageway
        /// </summary>
        [Required]
        [DataMember(Name="carriageway", EmitDefaultValue=false)]
        public CarriagewayEnumG VarCarriageway { get; set; }

        /// <summary>
        /// Gets or Sets OriginalNumberOfLanes
        /// </summary>
        [DataMember(Name="originalNumberOfLanes", EmitDefaultValue=true)]
        public int OriginalNumberOfLanes { get; set; }

        /// <summary>
        /// Gets or Sets Lane
        /// </summary>
        [DataMember(Name="lane", EmitDefaultValue=false)]
        public List<Lane> Lane { get; set; }

        /// <summary>
        /// Gets or Sets CarriagewayExtensionG
        /// </summary>
        [DataMember(Name="carriagewayExtensionG", EmitDefaultValue=false)]
        public Dictionary<string, Object> CarriagewayExtensionG { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Carriageway {\n");
            sb.Append("  VarCarriageway: ").Append(VarCarriageway).Append("\n");
            sb.Append("  OriginalNumberOfLanes: ").Append(OriginalNumberOfLanes).Append("\n");
            sb.Append("  Lane: ").Append(Lane).Append("\n");
            sb.Append("  CarriagewayExtensionG: ").Append(CarriagewayExtensionG).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Carriageway)obj);
        }

        /// <summary>
        /// Returns true if Carriageway instances are equal
        /// </summary>
        /// <param name="other">Instance of Carriageway to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Carriageway other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    VarCarriageway == other.VarCarriageway ||
                    VarCarriageway != null &&
                    VarCarriageway.Equals(other.VarCarriageway)
                ) && 
                (
                    OriginalNumberOfLanes == other.OriginalNumberOfLanes ||
                    
                    OriginalNumberOfLanes.Equals(other.OriginalNumberOfLanes)
                ) && 
                (
                    Lane == other.Lane ||
                    Lane != null &&
                    other.Lane != null &&
                    Lane.SequenceEqual(other.Lane)
                ) && 
                (
                    CarriagewayExtensionG == other.CarriagewayExtensionG ||
                    CarriagewayExtensionG != null &&
                    other.CarriagewayExtensionG != null &&
                    CarriagewayExtensionG.SequenceEqual(other.CarriagewayExtensionG)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (VarCarriageway != null)
                    hashCode = hashCode * 59 + VarCarriageway.GetHashCode();
                    
                    hashCode = hashCode * 59 + OriginalNumberOfLanes.GetHashCode();
                    if (Lane != null)
                    hashCode = hashCode * 59 + Lane.GetHashCode();
                    if (CarriagewayExtensionG != null)
                    hashCode = hashCode * 59 + CarriagewayExtensionG.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Carriageway left, Carriageway right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Carriageway left, Carriageway right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
