/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ExchangeInformation : IEquatable<ExchangeInformation>
    {
        /// <summary>
        /// Gets or Sets MessageType
        /// </summary>
        [DataMember(Name="messageType", EmitDefaultValue=false)]
        public MessageTypeEnumG MessageType { get; set; }

        /// <summary>
        /// Gets or Sets ExchangeContext
        /// </summary>
        [Required]
        [DataMember(Name="exchangeContext", EmitDefaultValue=false)]
        public ExchangeContext ExchangeContext { get; set; }

        /// <summary>
        /// Gets or Sets DynamicInformation
        /// </summary>
        [Required]
        [DataMember(Name="dynamicInformation", EmitDefaultValue=false)]
        public DynamicInformation DynamicInformation { get; set; }

        /// <summary>
        /// Gets or Sets ExchangeInformationExtensionG
        /// </summary>
        [DataMember(Name="exchangeInformationExtensionG", EmitDefaultValue=false)]
        public Dictionary<string, Object> ExchangeInformationExtensionG { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExchangeInformation {\n");
            sb.Append("  MessageType: ").Append(MessageType).Append("\n");
            sb.Append("  ExchangeContext: ").Append(ExchangeContext).Append("\n");
            sb.Append("  DynamicInformation: ").Append(DynamicInformation).Append("\n");
            sb.Append("  ExchangeInformationExtensionG: ").Append(ExchangeInformationExtensionG).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ExchangeInformation)obj);
        }

        /// <summary>
        /// Returns true if ExchangeInformation instances are equal
        /// </summary>
        /// <param name="other">Instance of ExchangeInformation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExchangeInformation other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MessageType == other.MessageType ||
                    MessageType != null &&
                    MessageType.Equals(other.MessageType)
                ) && 
                (
                    ExchangeContext == other.ExchangeContext ||
                    ExchangeContext != null &&
                    ExchangeContext.Equals(other.ExchangeContext)
                ) && 
                (
                    DynamicInformation == other.DynamicInformation ||
                    DynamicInformation != null &&
                    DynamicInformation.Equals(other.DynamicInformation)
                ) && 
                (
                    ExchangeInformationExtensionG == other.ExchangeInformationExtensionG ||
                    ExchangeInformationExtensionG != null &&
                    other.ExchangeInformationExtensionG != null &&
                    ExchangeInformationExtensionG.SequenceEqual(other.ExchangeInformationExtensionG)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (MessageType != null)
                    hashCode = hashCode * 59 + MessageType.GetHashCode();
                    if (ExchangeContext != null)
                    hashCode = hashCode * 59 + ExchangeContext.GetHashCode();
                    if (DynamicInformation != null)
                    hashCode = hashCode * 59 + DynamicInformation.GetHashCode();
                    if (ExchangeInformationExtensionG != null)
                    hashCode = hashCode * 59 + ExchangeInformationExtensionG.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ExchangeInformation left, ExchangeInformation right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ExchangeInformation left, ExchangeInformation right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
