/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// Gets or Sets ExchangeStatusEnum
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<ExchangeStatusEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ExchangeStatusEnum
        {
            
            /// <summary>
            /// Enum ClosingSessionEnum for closingSession
            /// </summary>
            [EnumMember(Value = "closingSession")]
            ClosingSessionEnum = 1,
            
            /// <summary>
            /// Enum OfflineEnum for offline
            /// </summary>
            [EnumMember(Value = "offline")]
            OfflineEnum = 2,
            
            /// <summary>
            /// Enum OnlineEnum for online
            /// </summary>
            [EnumMember(Value = "online")]
            OnlineEnum = 3,
            
            /// <summary>
            /// Enum OpeningSessionEnum for openingSession
            /// </summary>
            [EnumMember(Value = "openingSession")]
            OpeningSessionEnum = 4,
            
            /// <summary>
            /// Enum ResumingEnum for resuming
            /// </summary>
            [EnumMember(Value = "resuming")]
            ResumingEnum = 5,
            
            /// <summary>
            /// Enum UndefinedEnum for undefined
            /// </summary>
            [EnumMember(Value = "undefined")]
            UndefinedEnum = 6,
            
            /// <summary>
            /// Enum ExtendedGEnum for extendedG
            /// </summary>
            [EnumMember(Value = "extendedG")]
            ExtendedGEnum = 7
        }
}
