/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// Gets or Sets InvolvementRolesEnum
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<InvolvementRolesEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum InvolvementRolesEnum
        {
            
            /// <summary>
            /// Enum CyclistEnum for cyclist
            /// </summary>
            [EnumMember(Value = "cyclist")]
            CyclistEnum = 1,
            
            /// <summary>
            /// Enum MotorcyclistEnum for motorcyclist
            /// </summary>
            [EnumMember(Value = "motorcyclist")]
            MotorcyclistEnum = 2,
            
            /// <summary>
            /// Enum PedestrianEnum for pedestrian
            /// </summary>
            [EnumMember(Value = "pedestrian")]
            PedestrianEnum = 3,
            
            /// <summary>
            /// Enum UnknownEnum for unknown
            /// </summary>
            [EnumMember(Value = "unknown")]
            UnknownEnum = 4,
            
            /// <summary>
            /// Enum VehicleDriverEnum for vehicleDriver
            /// </summary>
            [EnumMember(Value = "vehicleDriver")]
            VehicleDriverEnum = 5,
            
            /// <summary>
            /// Enum VehicleOccupantEnum for vehicleOccupant
            /// </summary>
            [EnumMember(Value = "vehicleOccupant")]
            VehicleOccupantEnum = 6,
            
            /// <summary>
            /// Enum VehiclePassengerEnum for vehiclePassenger
            /// </summary>
            [EnumMember(Value = "vehiclePassenger")]
            VehiclePassengerEnum = 7,
            
            /// <summary>
            /// Enum WitnessEnum for witness
            /// </summary>
            [EnumMember(Value = "witness")]
            WitnessEnum = 8,
            
            /// <summary>
            /// Enum ExtendedGEnum for extendedG
            /// </summary>
            [EnumMember(Value = "extendedG")]
            ExtendedGEnum = 9
        }
}
