/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class NumberOfAxlesCharacteristic : IEquatable<NumberOfAxlesCharacteristic>
    {
        /// <summary>
        /// Gets or Sets ComparisonOperator
        /// </summary>
        [Required]
        [DataMember(Name="comparisonOperator", EmitDefaultValue=false)]
        public ComparisonOperatorEnumG ComparisonOperator { get; set; }

        /// <summary>
        /// Gets or Sets NumberOfAxles
        /// </summary>
        [Required]
        [DataMember(Name="numberOfAxles", EmitDefaultValue=true)]
        public int NumberOfAxles { get; set; }

        /// <summary>
        /// Gets or Sets NumberOfAxlesCharacteristicExtensionG
        /// </summary>
        [DataMember(Name="numberOfAxlesCharacteristicExtensionG", EmitDefaultValue=false)]
        public Dictionary<string, Object> NumberOfAxlesCharacteristicExtensionG { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NumberOfAxlesCharacteristic {\n");
            sb.Append("  ComparisonOperator: ").Append(ComparisonOperator).Append("\n");
            sb.Append("  NumberOfAxles: ").Append(NumberOfAxles).Append("\n");
            sb.Append("  NumberOfAxlesCharacteristicExtensionG: ").Append(NumberOfAxlesCharacteristicExtensionG).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((NumberOfAxlesCharacteristic)obj);
        }

        /// <summary>
        /// Returns true if NumberOfAxlesCharacteristic instances are equal
        /// </summary>
        /// <param name="other">Instance of NumberOfAxlesCharacteristic to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NumberOfAxlesCharacteristic other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ComparisonOperator == other.ComparisonOperator ||
                    ComparisonOperator != null &&
                    ComparisonOperator.Equals(other.ComparisonOperator)
                ) && 
                (
                    NumberOfAxles == other.NumberOfAxles ||
                    
                    NumberOfAxles.Equals(other.NumberOfAxles)
                ) && 
                (
                    NumberOfAxlesCharacteristicExtensionG == other.NumberOfAxlesCharacteristicExtensionG ||
                    NumberOfAxlesCharacteristicExtensionG != null &&
                    other.NumberOfAxlesCharacteristicExtensionG != null &&
                    NumberOfAxlesCharacteristicExtensionG.SequenceEqual(other.NumberOfAxlesCharacteristicExtensionG)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ComparisonOperator != null)
                    hashCode = hashCode * 59 + ComparisonOperator.GetHashCode();
                    
                    hashCode = hashCode * 59 + NumberOfAxles.GetHashCode();
                    if (NumberOfAxlesCharacteristicExtensionG != null)
                    hashCode = hashCode * 59 + NumberOfAxlesCharacteristicExtensionG.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(NumberOfAxlesCharacteristic left, NumberOfAxlesCharacteristic right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(NumberOfAxlesCharacteristic left, NumberOfAxlesCharacteristic right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
