/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class OverallPeriod : IEquatable<OverallPeriod>
    {
        /// <summary>
        /// Gets or Sets OverallStartTime
        /// </summary>
        [Required]
        [DataMember(Name="overallStartTime", EmitDefaultValue=true)]
        public DateTime OverallStartTime { get; set; }

        /// <summary>
        /// Gets or Sets OverallEndTime
        /// </summary>
        [DataMember(Name="overallEndTime", EmitDefaultValue=true)]
        public DateTime OverallEndTime { get; set; }

        /// <summary>
        /// Gets or Sets OverallPeriodExtensionG
        /// </summary>
        [DataMember(Name="overallPeriodExtensionG", EmitDefaultValue=false)]
        public Dictionary<string, Object> OverallPeriodExtensionG { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OverallPeriod {\n");
            sb.Append("  OverallStartTime: ").Append(OverallStartTime).Append("\n");
            sb.Append("  OverallEndTime: ").Append(OverallEndTime).Append("\n");
            sb.Append("  OverallPeriodExtensionG: ").Append(OverallPeriodExtensionG).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((OverallPeriod)obj);
        }

        /// <summary>
        /// Returns true if OverallPeriod instances are equal
        /// </summary>
        /// <param name="other">Instance of OverallPeriod to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OverallPeriod other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    OverallStartTime == other.OverallStartTime ||
                    
                    OverallStartTime.Equals(other.OverallStartTime)
                ) && 
                (
                    OverallEndTime == other.OverallEndTime ||
                    
                    OverallEndTime.Equals(other.OverallEndTime)
                ) && 
                (
                    OverallPeriodExtensionG == other.OverallPeriodExtensionG ||
                    OverallPeriodExtensionG != null &&
                    other.OverallPeriodExtensionG != null &&
                    OverallPeriodExtensionG.SequenceEqual(other.OverallPeriodExtensionG)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + OverallStartTime.GetHashCode();
                    
                    hashCode = hashCode * 59 + OverallEndTime.GetHashCode();
                    if (OverallPeriodExtensionG != null)
                    hashCode = hashCode * 59 + OverallPeriodExtensionG.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(OverallPeriod left, OverallPeriod right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(OverallPeriod left, OverallPeriod right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
