/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// Gets or Sets ProtocolTypeEnum
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<ProtocolTypeEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ProtocolTypeEnum
        {
            
            /// <summary>
            /// Enum DeltaPullEnum for deltaPull
            /// </summary>
            [EnumMember(Value = "deltaPull")]
            DeltaPullEnum = 1,
            
            /// <summary>
            /// Enum DeltaPushEnum for deltaPush
            /// </summary>
            [EnumMember(Value = "deltaPush")]
            DeltaPushEnum = 2,
            
            /// <summary>
            /// Enum OtherEnum for other
            /// </summary>
            [EnumMember(Value = "other")]
            OtherEnum = 3,
            
            /// <summary>
            /// Enum SimpleCISEnum for simpleCIS
            /// </summary>
            [EnumMember(Value = "simpleCIS")]
            SimpleCISEnum = 4,
            
            /// <summary>
            /// Enum SimplePushEnum for simplePush
            /// </summary>
            [EnumMember(Value = "simplePush")]
            SimplePushEnum = 5,
            
            /// <summary>
            /// Enum SnapshotPullEnum for snapshotPull
            /// </summary>
            [EnumMember(Value = "snapshotPull")]
            SnapshotPullEnum = 6,
            
            /// <summary>
            /// Enum SnapshotPushEnum for snapshotPush
            /// </summary>
            [EnumMember(Value = "snapshotPush")]
            SnapshotPushEnum = 7,
            
            /// <summary>
            /// Enum StatefulCISEnum for statefulCIS
            /// </summary>
            [EnumMember(Value = "statefulCIS")]
            StatefulCISEnum = 8,
            
            /// <summary>
            /// Enum StatefulPushEnum for statefulPush
            /// </summary>
            [EnumMember(Value = "statefulPush")]
            StatefulPushEnum = 9,
            
            /// <summary>
            /// Enum ExtendedGEnum for extendedG
            /// </summary>
            [EnumMember(Value = "extendedG")]
            ExtendedGEnum = 10
        }
}
