/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// Gets or Sets ValidityStatusEnum
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<ValidityStatusEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ValidityStatusEnum
        {
            
            /// <summary>
            /// Enum ActiveEnum for active
            /// </summary>
            [EnumMember(Value = "active")]
            ActiveEnum = 1,
            
            /// <summary>
            /// Enum PlannedEnum for planned
            /// </summary>
            [EnumMember(Value = "planned")]
            PlannedEnum = 2,
            
            /// <summary>
            /// Enum SuspendedEnum for suspended
            /// </summary>
            [EnumMember(Value = "suspended")]
            SuspendedEnum = 3,
            
            /// <summary>
            /// Enum DefinedByValidityTimeSpecEnum for definedByValidityTimeSpec
            /// </summary>
            [EnumMember(Value = "definedByValidityTimeSpec")]
            DefinedByValidityTimeSpecEnum = 4,
            
            /// <summary>
            /// Enum ExtendedGEnum for extendedG
            /// </summary>
            [EnumMember(Value = "extendedG")]
            ExtendedGEnum = 5
        }
}
