/*
 * DATEX II Snapshot Pull API
 *
 * This is DATEX II Snapshot PULL API returning PayloadPublication.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// Gets or Sets VehicleTypeEnum
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<VehicleTypeEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum VehicleTypeEnum
        {
            
            /// <summary>
            /// Enum AgriculturalVehicleEnum for agriculturalVehicle
            /// </summary>
            [EnumMember(Value = "agriculturalVehicle")]
            AgriculturalVehicleEnum = 1,
            
            /// <summary>
            /// Enum AnyVehicleEnum for anyVehicle
            /// </summary>
            [EnumMember(Value = "anyVehicle")]
            AnyVehicleEnum = 2,
            
            /// <summary>
            /// Enum ArticulatedBusEnum for articulatedBus
            /// </summary>
            [EnumMember(Value = "articulatedBus")]
            ArticulatedBusEnum = 3,
            
            /// <summary>
            /// Enum ArticulatedTrolleyBusEnum for articulatedTrolleyBus
            /// </summary>
            [EnumMember(Value = "articulatedTrolleyBus")]
            ArticulatedTrolleyBusEnum = 4,
            
            /// <summary>
            /// Enum ArticulatedVehicleEnum for articulatedVehicle
            /// </summary>
            [EnumMember(Value = "articulatedVehicle")]
            ArticulatedVehicleEnum = 5,
            
            /// <summary>
            /// Enum BicycleEnum for bicycle
            /// </summary>
            [EnumMember(Value = "bicycle")]
            BicycleEnum = 6,
            
            /// <summary>
            /// Enum BusEnum for bus
            /// </summary>
            [EnumMember(Value = "bus")]
            BusEnum = 7,
            
            /// <summary>
            /// Enum CarEnum for car
            /// </summary>
            [EnumMember(Value = "car")]
            CarEnum = 8,
            
            /// <summary>
            /// Enum CaravanEnum for caravan
            /// </summary>
            [EnumMember(Value = "caravan")]
            CaravanEnum = 9,
            
            /// <summary>
            /// Enum CarOrLightVehicleEnum for carOrLightVehicle
            /// </summary>
            [EnumMember(Value = "carOrLightVehicle")]
            CarOrLightVehicleEnum = 10,
            
            /// <summary>
            /// Enum CarWithCaravanEnum for carWithCaravan
            /// </summary>
            [EnumMember(Value = "carWithCaravan")]
            CarWithCaravanEnum = 11,
            
            /// <summary>
            /// Enum CarWithTrailerEnum for carWithTrailer
            /// </summary>
            [EnumMember(Value = "carWithTrailer")]
            CarWithTrailerEnum = 12,
            
            /// <summary>
            /// Enum ConstructionOrMaintenanceVehicleEnum for constructionOrMaintenanceVehicle
            /// </summary>
            [EnumMember(Value = "constructionOrMaintenanceVehicle")]
            ConstructionOrMaintenanceVehicleEnum = 13,
            
            /// <summary>
            /// Enum FourWheelDriveEnum for fourWheelDrive
            /// </summary>
            [EnumMember(Value = "fourWheelDrive")]
            FourWheelDriveEnum = 14,
            
            /// <summary>
            /// Enum HeavyGoodsVehicleEnum for heavyGoodsVehicle
            /// </summary>
            [EnumMember(Value = "heavyGoodsVehicle")]
            HeavyGoodsVehicleEnum = 15,
            
            /// <summary>
            /// Enum HeavyGoodsVehicleWithTrailerEnum for heavyGoodsVehicleWithTrailer
            /// </summary>
            [EnumMember(Value = "heavyGoodsVehicleWithTrailer")]
            HeavyGoodsVehicleWithTrailerEnum = 16,
            
            /// <summary>
            /// Enum HeavyDutyTransporterEnum for heavyDutyTransporter
            /// </summary>
            [EnumMember(Value = "heavyDutyTransporter")]
            HeavyDutyTransporterEnum = 17,
            
            /// <summary>
            /// Enum HeavyVehicleEnum for heavyVehicle
            /// </summary>
            [EnumMember(Value = "heavyVehicle")]
            HeavyVehicleEnum = 18,
            
            /// <summary>
            /// Enum HighSidedVehicleEnum for highSidedVehicle
            /// </summary>
            [EnumMember(Value = "highSidedVehicle")]
            HighSidedVehicleEnum = 19,
            
            /// <summary>
            /// Enum LightCommercialVehicleEnum for lightCommercialVehicle
            /// </summary>
            [EnumMember(Value = "lightCommercialVehicle")]
            LightCommercialVehicleEnum = 20,
            
            /// <summary>
            /// Enum LargeCarEnum for largeCar
            /// </summary>
            [EnumMember(Value = "largeCar")]
            LargeCarEnum = 21,
            
            /// <summary>
            /// Enum LargeGoodsVehicleEnum for largeGoodsVehicle
            /// </summary>
            [EnumMember(Value = "largeGoodsVehicle")]
            LargeGoodsVehicleEnum = 22,
            
            /// <summary>
            /// Enum LightCommercialVehicleWithTrailerEnum for lightCommercialVehicleWithTrailer
            /// </summary>
            [EnumMember(Value = "lightCommercialVehicleWithTrailer")]
            LightCommercialVehicleWithTrailerEnum = 23,
            
            /// <summary>
            /// Enum LongHeavyLorryEnum for longHeavyLorry
            /// </summary>
            [EnumMember(Value = "longHeavyLorry")]
            LongHeavyLorryEnum = 24,
            
            /// <summary>
            /// Enum LorryEnum for lorry
            /// </summary>
            [EnumMember(Value = "lorry")]
            LorryEnum = 25,
            
            /// <summary>
            /// Enum MetroEnum for metro
            /// </summary>
            [EnumMember(Value = "metro")]
            MetroEnum = 26,
            
            /// <summary>
            /// Enum MinibusEnum for minibus
            /// </summary>
            [EnumMember(Value = "minibus")]
            MinibusEnum = 27,
            
            /// <summary>
            /// Enum MopedEnum for moped
            /// </summary>
            [EnumMember(Value = "moped")]
            MopedEnum = 28,
            
            /// <summary>
            /// Enum MotorcycleEnum for motorcycle
            /// </summary>
            [EnumMember(Value = "motorcycle")]
            MotorcycleEnum = 29,
            
            /// <summary>
            /// Enum MotorcycleWithSideCarEnum for motorcycleWithSideCar
            /// </summary>
            [EnumMember(Value = "motorcycleWithSideCar")]
            MotorcycleWithSideCarEnum = 30,
            
            /// <summary>
            /// Enum MotorhomeEnum for motorhome
            /// </summary>
            [EnumMember(Value = "motorhome")]
            MotorhomeEnum = 31,
            
            /// <summary>
            /// Enum MotorscooterEnum for motorscooter
            /// </summary>
            [EnumMember(Value = "motorscooter")]
            MotorscooterEnum = 32,
            
            /// <summary>
            /// Enum PassengerCarEnum for passengerCar
            /// </summary>
            [EnumMember(Value = "passengerCar")]
            PassengerCarEnum = 33,
            
            /// <summary>
            /// Enum SmallCarEnum for smallCar
            /// </summary>
            [EnumMember(Value = "smallCar")]
            SmallCarEnum = 34,
            
            /// <summary>
            /// Enum TankerEnum for tanker
            /// </summary>
            [EnumMember(Value = "tanker")]
            TankerEnum = 35,
            
            /// <summary>
            /// Enum ThreeWheeledVehicleEnum for threeWheeledVehicle
            /// </summary>
            [EnumMember(Value = "threeWheeledVehicle")]
            ThreeWheeledVehicleEnum = 36,
            
            /// <summary>
            /// Enum TrailerEnum for trailer
            /// </summary>
            [EnumMember(Value = "trailer")]
            TrailerEnum = 37,
            
            /// <summary>
            /// Enum TramEnum for tram
            /// </summary>
            [EnumMember(Value = "tram")]
            TramEnum = 38,
            
            /// <summary>
            /// Enum TrolleyBusEnum for trolleyBus
            /// </summary>
            [EnumMember(Value = "trolleyBus")]
            TrolleyBusEnum = 39,
            
            /// <summary>
            /// Enum TwoWheeledVehicleEnum for twoWheeledVehicle
            /// </summary>
            [EnumMember(Value = "twoWheeledVehicle")]
            TwoWheeledVehicleEnum = 40,
            
            /// <summary>
            /// Enum VanEnum for van
            /// </summary>
            [EnumMember(Value = "van")]
            VanEnum = 41,
            
            /// <summary>
            /// Enum VehicleWithCaravanEnum for vehicleWithCaravan
            /// </summary>
            [EnumMember(Value = "vehicleWithCaravan")]
            VehicleWithCaravanEnum = 42,
            
            /// <summary>
            /// Enum VehicleWithCatalyticConverterEnum for vehicleWithCatalyticConverter
            /// </summary>
            [EnumMember(Value = "vehicleWithCatalyticConverter")]
            VehicleWithCatalyticConverterEnum = 43,
            
            /// <summary>
            /// Enum VehicleWithoutCatalyticConverterEnum for vehicleWithoutCatalyticConverter
            /// </summary>
            [EnumMember(Value = "vehicleWithoutCatalyticConverter")]
            VehicleWithoutCatalyticConverterEnum = 44,
            
            /// <summary>
            /// Enum VehicleWithTrailerEnum for vehicleWithTrailer
            /// </summary>
            [EnumMember(Value = "vehicleWithTrailer")]
            VehicleWithTrailerEnum = 45,
            
            /// <summary>
            /// Enum WithEvenNumberedRegistrationPlatesEnum for withEvenNumberedRegistrationPlates
            /// </summary>
            [EnumMember(Value = "withEvenNumberedRegistrationPlates")]
            WithEvenNumberedRegistrationPlatesEnum = 46,
            
            /// <summary>
            /// Enum WithOddNumberedRegistrationPlatesEnum for withOddNumberedRegistrationPlates
            /// </summary>
            [EnumMember(Value = "withOddNumberedRegistrationPlates")]
            WithOddNumberedRegistrationPlatesEnum = 47,
            
            /// <summary>
            /// Enum UnknownEnum for unknown
            /// </summary>
            [EnumMember(Value = "unknown")]
            UnknownEnum = 48,
            
            /// <summary>
            /// Enum OtherEnum for other
            /// </summary>
            [EnumMember(Value = "other")]
            OtherEnum = 49,
            
            /// <summary>
            /// Enum ExtendedGEnum for extendedG
            /// </summary>
            [EnumMember(Value = "extendedG")]
            ExtendedGEnum = 50
        }
}
